name: The Film Dream Publishing
analytics:
  google: UA-64070424-1
purpose:
  - type: external
    url: 'http://thefilmdream.com'
    label: 'http://thefilmdream.com'
  - type: contact
    url: 'mailto:thefilmdream@icloud.com'
    label: Let's collaborate!
github: true
description: Arts & Culture For a Better You!
author:
  name: The Film Dream Publishing
  url: 'http://thefilmdream.com'
  email: thefilmdream@icloud.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/71f802de-bce8-450d-bcf7-1e3d7b53a05c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/71f802de-bce8-450d-bcf7-1e3d7b53a05c.jpg
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - id: fb48f60c-abd4-428f-94de-444f79163ffc
    name: About us
    type: content
  - id: a7656111-b1e2-453d-b43a-3e6eb7a731eb
    name: What's Happening?
    type: content
  - id: 362f78b6-7ec8-4ffe-9f0c-05f374ab0580
    name: Adventures & Inspirations
    type: content
layout_spectrum: 0.47699650527365356
color:
  lightness: 0.34925251467171875
  brandColors:
    - '#067EBB'
    - '#D9DCD3'
    - '#032D77'
    - '#E4A756'
    - '#8A5A50'
  saturation: 0.016968866999141206
  brandStrength: 0.6026103073551254
  rhythmicContrast: 0.279898667645613
content_rating:
  adult: false
typography_spectrum: 0.31580420796206166
opengraph: {}
title: Of Inspirations & Adventures
